### PR TITLE
raise an error if a built resource is present in source and the names conflicts

### LINKED ISSUE #111: Several plugin ZIPs using QGIS Plugin CI have duplicated files inside
For some reason I downloaded all QGIS plugins and extracted them. I noticed an issue and it looks like QGIS Plugin CI is a common demoninator. If it is not the cause, sorry! :)

`resources.py` is included twice in 5 plugins:

- https://github.com/opengisch/qgis-swiss-locator/issues/36
- https://github.com/dsgoficial/DSGToolsOp/issues/36
- https://github.com/phborba/DeepLearningTools/issues/9
- https://forge.chapril.org/linux_alpes/caliec/ (no issue filed because no account)
- https://gitlab.com/Oslandia/qgis/qompligis (no issue filed because no account)

They all seem to use QGIS Plugin CI so I wonder if this is caused by some bug in it or misconfiguration at the plugin CIs?

### PR DESCRIPTION
**Pull request by 3nids**
fixes #111

### CODE REVIEW

**Comment by 3nids** [comment]
@Gustry @Guts  what do you think?
if it's OK, I'll release and give it a shot on swiss-locator to see if correctly fails

**Comment by 3nids** [comment]
@kannes is this acceptable for you that the plugin-ci raises an error in such scenario?

**Comment by kannes** [comment]
> @kannes is this acceptable for you that the plugin-ci raises an error in such scenario?

I can't judge it as I have not used this great piece of software myself yet and would not know when it happens and how. As mere messenger of the issue any solution is acceptable ;)

**Comment by Guts** [comment]
@3nids maybe a warning is enough if it's just a "cosmetic" issue?

**Comment by 3nids** [comment]
It might be a bit more than cosmetic if the compiled file in the source is outdated

**Review by Guts — APPROVED** [review]

**Review by Gustry — APPROVED** [review]

**Pull request merged**
