### PR TITLE
Use underscore instead of hyphen for plugin name #22

### LINKED ISSUE #22: Plugin name with spaces are not well detected by QGIS
We have a few plugins with a space in their name.
When using the `plugins.xml` generated by the plugin, we are noticing that QGIS is confused about the name.

For instance, we have this plugin https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin
The plugin is named/located in the `veloroutes_voies_vertes` directory.

The plugins.xml generated by qgis-plugin-ci will have:

```xml
<file_name>veloroutes-voies-vertes.0.2.0.zip</file_name>
<download_url>https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/releases/download/0.2.0/veloroutes-voies-vertes.0.2.0.zip</download_url>
```

When I install it using the `plugins.xml`, QGIS will be confused because QGIS will extract the folder with `veloroutes_voies_vertes` while QGIS will look for a folder `veloroutes-voies-vertes`. A warning is raised in the plugin manager saying that the plugin went somewhere but not in the correct directory (because the folder `veloroutes-voies-vertes` does not exist after extraction).

Don't you have this issue too?
The `filename` parameter in the plugins.xml should be filled with the correct plugin name IMHO.

### PR DESCRIPTION
**Pull request by Gustry**
I can't really run tests locally, let's check Travis.

Fix #22

### CODE REVIEW

**Comment by Gustry** [comment]
It seems the test is using the online plugins.xml @3nids ?
https://github.com/opengisch/qgis-plugin-ci/blob/master/test/test_release.py#L71

**Comment by 3nids** [comment]
you need to update the expected file: https://github.com/opengisch/qgis-plugin-ci/blob/master/test/plugins.xml.expected

**Comment by Gustry** [comment]
Didn't I ?
https://github.com/opengisch/qgis-plugin-ci/pull/23/files

**Comment by 3nids** [comment]
sorry yes, see last commit in this branch

**Comment by Gustry** [comment]
Arf ok, I was confused by `'-experimental' `-testing`. My bad.

After this PR is merged, can you release a new version? Thanks.

**Comment by 3nids** [comment]
done: https://github.com/opengisch/qgis-plugin-ci/releases/tag/1.8.1

**Pull request merged**
