### PR TITLE
Dev tooling

### PR DESCRIPTION
**Pull request by Guts**
- use precommit hooks: remove encoding pragma, trailing whitespaces...
- format the code using black
- sort imports (isort)

### CODE REVIEW

**Comment by 3nids** [comment]
Any idea why tests are failing?

**Comment by 3nids** [comment]
The installation of requirements in the CI is missing (nose2 is not installed)

**Review by Gustry — COMMENTED** [review]
LGTM

**Comment by 3nids** [comment]
@Guts any chance to fix the Changelog test? They are failiing since then.
Let me know if you prefer me to revert?

**Comment by Guts** [comment]
I try to get time on it until tomorrow night. On Wednesday, if I did not nothing, feel free to revert. Deadline deal?

**Pull request merged**
