### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by Djedouas**
Refactorisation of unit tests to

- improve stability
- improve robustness
- improve logging

### CODE REVIEW

**Comment by 3nids** [comment]
It looks like the tests will be run twice on pull requests no?
Is this a work in progress?

(We have the issue that the tests cannot be run from a fork due to the secrets to access transifex).

**Comment by Djedouas** [comment]
> It looks like the tests will be run twice on pull requests no?

yes

> Is this a work in progress?

Absolutely !

**Comment by 3nids** [comment]
Is there anything to discuss here?

**Comment by Djedouas** [comment]
@3nids I am trying to understand why the release https://github.com/opengisch/qgis-plugin-ci/releases/tag/0.1.2 should not be removed.

It seems to me that in the current testing flow it wouldn't matter, could you please point to me where the problem would be?

Thanks

**Comment by 3nids** [comment]
Here you go https://github.com/opengisch/qgis-plugin-ci/blob/e6acc22047693c9d5d33e1075e00c37846e804ad/test/test_release.py#L30

**Comment by Djedouas** [comment]
Yes I found that but I don't see why the release should be already existing on github

**Comment by Djedouas** [comment]
OK I see here

https://github.com/opengisch/qgis-plugin-ci/blob/e6acc22047693c9d5d33e1075e00c37846e804ad/qgispluginci/release.py#L266

that the code assumes that the release already exists, I guess because we assume that another github ci action did it, I am right?

**Comment by 3nids** [comment]
Two reasons:
I usually do it this way (create the release on GitHub which triggers the release process)
If I would delete/recreate it, it would be listed first as the latest release (if the job fails and release remains) and people would get notified of the release creation.

**Comment by 3nids** [comment]
I am closing this due to lack of activity/content. Feel free to re-open / discuss about possible improvements for tests (removing the transifex integration is the critical point to me)

**Pull request closed without merging**
