### PR TITLE
Release/include qm

### LINKED ISSUE #47: Release: compiled translations are not included into final zip
To reproduce:

1. compile translations (typically: `lrelease {plugin}/resources/i18n/*.ts`)
2. run qgis-plugin-ci release

Result:

- *.ts files are included
- but not the *.qm files

Should be the reverse no?

### PR DESCRIPTION
**Pull request by Guts**
Close #47 

This PR:

- make the translation module independent from a specific service (here transifex)
- implement the logic to process local translations (CLI options, etc.)
- minor improvments

### CODE REVIEW

**Review by Gustry — COMMENTED** [review]
Looks fine, thanks

Can you update the sphinx documentation ?

**Comment by 3nids** [comment]
I am wondering if we should not go a bit further.

The transifex integration has always been a pain in plugin-ci (we rely on a [self-made Python lib](https://github.com/opengisch/pytransifex) for it, it prevents from running parallel test jobs).

For the translations, at the moment we cannot avoid using a sub-process to update and compile strings (see https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/translation.py#L125-L143).

So I am wondering if we should not just make the translation completely agnostic of any platform.
We could just provide pull/push commands as strings in the config that we would run using sub-process (or we hardcode them if that sounds too bad i.e.: `if transifex: subprocess.run(tx_pull_cmd)`)

The only drawback of this would be that the project won't be created automatically anymore on Transifex (which is super useful to me as I don't need to head to transifex at all).

Thoughts?

**Comment by Guts** [comment]
I completely agree.

The tool creates an amalgam between translation management and a third party service (transifex). Besides, the ecosystem now seems to react positively to the emergence of [weblate](https://weblate.osgeo.org/) and it's a shame not to offer it or rather to impose transifex.

More globally, the tool is currently very much imprinted with our respective development habits whereas I think it would gain in adoption to be more generic/agnostic.

But I think it implies a refactoring.

**Comment by Guts** [comment]
Furthermore, speaking of this (almost stale) PR, I've managed my needs by manipulating the gitignore to include qm files without adding them to the tracking files (let's argue against binary files into a git repo). [Workflow example](https://github.com/geotribu/qtribu/actions/runs/1998090726):

1. build/compile translations from ts and pro files and upload build result as artifact: [example](https://github.com/geotribu/qtribu/blob/main/.github/workflows/packager.yml#L12-L35)
2. download it, amend the git ignore and add qm file to tracked files: [example](https://github.com/geotribu/qtribu/blob/main/.github/workflows/packager.yml#L67-L79)

**Comment by 3nids** [comment]
To add to the topic, we lately changed our habits.
In the past, we were only having the TS files on the remote service and download them when needed. 
Lately, we tend to see them as being part of the source.

**Pull request closed without merging**
