### PR TITLE
Make changelog real again

### PR DESCRIPTION
**Pull request by Guts**
For now, the CHANGELOG.md is a fake and used for test goals. This PR:

- move this one as a test fixture
- create a new and real changelog for the project

See https://github.com/opengisch/qgis-plugin-ci/issues/31#issuecomment-777192574

### CODE REVIEW

**Comment by Gustry** [comment]
Can I merge #37 first ? :)
Because you need to update the test to find the fake changelog

But maybe @3nids doesn't want to maintain the changelog file ? (as mentioned, he is doing the release from Github) :p

**Comment by Guts** [comment]
> Can I merge #37 first ? :)

Sure!

**Comment by 3nids** [comment]
Well, we can populate the changelog from the release....
More seriously, It'd be nice the other way around: update the release notes from the changelog. But no biggie.

I'm +0 on this. Not so happy to maintain a changelog, but I guess it's the road to a more professional tool. Good job guys!

**Comment by Guts** [comment]
> More seriously, It'd be nice the other way around: update the release notes from the changelog. But no biggie.

Completely possible.

> but I guess it's the road to a more professional tool. 

I'm pretty confident about the future global use of this plugin across the QGIS plugins ecosystem. I think to write about it on [Geotribu](https://static.geotribu.fr) to give it a simple tutorial in French and plan to share this tool at Oslandia. With 3Liz already in the loop, there are such a good "QGIS related team", no? :)

**Comment by 3nids** [comment]
> I'm pretty confident about the future global use of this plugin across the QGIS plugins ecosystem. I think to write about it on Geotribu to give it a simple tutorial in French and plan to share this tool at Oslandia. With 3Liz already in the loop, there are such a good "QGIS related team", no? :)

Totally, it's really cool to see it embraced by others!

**Comment by 3nids** [comment]
feel free to merge when you feel like to.

**Comment by Gustry** [comment]
@Guts This changelog file is used in the tests so now the CI is failing, also my changes from #37 are lost.

I thought you were going to update the test to find the correct changelog file :)

**Comment by Guts** [comment]
> @Guts This changelog file is used in the tests so now the CI is failing, also my changes from #37 are lost.
> 
> I thought you were going to update the test to find the correct changelog file :)

Oupsiii. Sorry! Don't hesitate in reverting my commits

**Pull request merged**
