### PR TITLE
rename gallery to examples

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by Guts** [comment]
Oh I just remembered that I was planning to use https://sphinx-panels.readthedocs.io/en/latest/ to display gallery of examples!  
Do you want to try it in this PR or not?

**Comment by 3nids** [comment]
Feel free!

**Review by Guts — APPROVED** [review]

**Comment by Guts** [comment]
> Oh I just remembered that I was planning to use https://sphinx-panels.readthedocs.io/en/latest/ to display gallery of examples!

Done. A good opportunity to try this. What do you think?

image

**Comment by Guts** [comment]
@3nids I think it's ready

**Pull request merged**
