### PR TITLE
Use the plugin folder to create the zip

### PR DESCRIPTION
**Pull request by Gustry**
* Rename the included testing plugin to have capital letters
* Use the plugin folder for creating the zip file

Explanation, I found another plugin having capital letters in its plugin name metadata.txt. The slugify function will lower this title for the zip name.
But the folder itself has capital letters as well, so the QGIS plugin manager is confused about the difference with the zip and the included folder.

I think we should remove the logic to build the zip file name and just use the folder name where the source code is located. No?
It up to the developer to have a correct folder name.

### CODE REVIEW

**Comment by Gustry** [comment]
Gentle ping @3nids What do you think of this approach?

**Comment by 3nids** [comment]
Thanks!

**Comment by Gustry** [comment]
Thanks for the merge! Can you make a tag?

**Comment by Gustry** [comment]
Ok I saw it !
Cool !

**Pull request merged**
