### PR TITLE
Support for pyproject.toml

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
_Adding support for pyproject.toml files_
- pyproject.toml are becoming the standard nowadays for packaging Python applications so I felt it would be nice to offer that
- did some DRY-cleaning, moving the logic initializing the argparse Parameters to a stand-alone top level function; it could be an instance method of Parameters too, it's easy to refactor from  one to the other
- added tests leveraging the two aforementioned changes
- reduced time complexity when collecting metadata
- sprinkled some type hints here and there.

### CODE REVIEW

**Comment by 3nids** [comment]
@why-not-try-calmer thanks a lot for this contribution!
This sounds good to me.

@Gustry @Guts ok for you?
If we decide to move to a version 2.x, I'd rather keel the `.qgis-plugin-ci.yaml` and completely move to `pyproject.toml`. Any thoughts?

**Comment by Gustry** [comment]
LGTM, thanks :)

> If we decide to move to a version 2.x, I'd rather keel the .qgis-plugin-ci.yaml and completely move to pyproject.toml. Any thoughts?

Fine for me, I have never used it :)

**Comment by Guts** [comment]
Good move!

> @Gustry @Guts ok for you? If we decide to move to a version 2.x, I'd rather keel the `.qgis-plugin-ci.yaml` and completely move to `pyproject.toml`. Any thoughts?

If the `setup.cfg` section is still supported it's fine to me. I've never used the `.qgis-plugin-ci.yaml` file.

**Comment by why-not-try-calmer** [comment]
> Good move!
> 
> > @Gustry @Guts ok for you? If we decide to move to a version 2.x, I'd rather keel the `.qgis-plugin-ci.yaml` and completely move to `pyproject.toml`. Any thoughts?
> 
> If the `setup.cfg` section is still supported it's fine to me. I've never used the `.qgis-plugin-ci.yaml` file.

The `setup.cfg` is still supported as per this PR. `.qgis-plugin-ci` is not a YAML file, just a plain text file which follows more or less the format convention of "environment variables"-files.

**Comment by Gustry** [comment]
In the documentation in the MD file, I meant mainly line 6 at the top of the file.

Thanks @why-not-try-calmer

**Comment by why-not-try-calmer** [comment]
> In the documentation in the MD file, I meant mainly line 6 at the top of the file.
> 
> Thanks @why-not-try-calmer

Done.

Independently of this PR I'd suggest suffixing files that meet a specific format (i.e. .qgis-plugin-ci -> .qgis-plugin-ci.yml).

**Review by Gustry — APPROVED** [review]

**Pull request merged**
